// HARDWARE
#define PWM_CHANNEL_1 2
#define PWM_CHANNEL_2 3
#define PWM_CHANNEL_3 18
#define LEDPIN 13

// SCHEDULING
#define BLINK_INTERVAL 200
#define PRINT_INTERVAL 20

// SERIAL
#define BAUDRATE_PC 115200
